config/routes.rb
Rails.application.routes.draw do

  root 'main/landing#index'
  get 'handler/error' => 'main/landing#error'

  get 'cgu' => 'main/landing#cgu'

  #devise_for :users
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  scope 'superadmin', module: 'superadmin', as: "superadmin" do
    get '/' => 'dashboard#index'
    resources :sites
    resources :users
    resources :products
    get 'sale' => "products#sale"
  end


  scope ':site/admin', module: 'admin', as: "admin" do
    get '/' => "dashboard#index"
    get 'update_template' => "templates#update_template"
    resources :templates

    resources :articles
    resources :categories
    resources :tabs , except: [:index, :show ]

    resources :comments, except: [:new, :create, :update, :edit ]

    resources :products
    resources :plugins, except: [:new, :create ]
    resources :carts
    resources :cart_products
    resources :orders, except: [ :update, :edit, :destroy ]
    get '/admin/cart_products/:product_id' => 'carts#add', as: 'add_product_in_cart'
    get '/remove/:product_id' => 'carts#remove', as: 'remove_product_in_cart'

    post 'pay' => 'orders#pay'
    get 'buy' => 'orders#buy'
    get 'new_tab_category'      => 'tabs#new_tab_category'

    get '/menu' => 'tabs#index'

    resources :sites, except: [:index, :new, :show, :create, :destroy ]
    get '/site/configuration' => 'sites#edit'


    get 'dashboard/index' => "dashboard#index"
    get '*path',   :to => 'dashboard#error'

  end

  post ":site/new_comment" => "handler#new_comment"

  get ':site'                 => "handler#web"
  get ':site/:slug1'          => "handler#web"
  get ':site/:slug1/:slug2'   => "handler#web"

  namespace :main do
    get 'landing/index'
    get 'landing/show'

  end
  namespace :web do
    get 'main/index'
    get 'main/show'

  end

  namespace :admin do
    get 'dashboard/index'
    get 'dashboard/show'
    get 'dashboard/login'
    get 'dashboard/signup'
  end


end

app/controllers/admin/dashboard_controller.rb
module Admin
  class Admin::DashboardController < Admin::ApplicationController

    def index
      @nb_articles     = Article.where(site: @site).count
      @nb_categories   = Category.where(site: @site).count
      @nb_commentaires = Comment.where(article: @user.articles.ids).count
      @articles        = Article.where(site: @site).all.order("created_at DESC").limit(5)
      @comments        = Comment.where(article: @user.articles.ids).order("created_at DESC").limit(5)
    end

    def error
    end
  end
end

app/controllers/superadmin/dashboard_controller.rb
module Superadmin
  class DashboardController < Superadmin::ApplicationController
    def index
      @nb_user = User.all.count - 1
      @nb_site = Site.all.count
      @nb_article = Article.all.count
    end
  end
end

app/views/superadmin/dashboard/shared/_footer.html.erb
                <footer class="footer text-right">
                    2018 © Polygones
                </footer>

app/views/superadmin/dashboard/shared/_header.html.erb
<div id="wrapper">

            <!-- Top Bar Start -->
            <div class="topbar">

                <!-- LOGO -->
                <div class="topbar-left">
                    <%= link_to superadmin_path, class: "logo" do%>
                        <span>
                            <%= image_tag 'admin/dashboard/logo.png', height:'32' %>
                        </span>
                        <i>
                            <%= image_tag 'admin/dashboard/logo_sm.png', height:'32' %>
                        </i>
                    <% end %>
                </div>

                <nav class="navbar-custom">

                    <ul class="list-inline float-right mb-0">

                        <li class="list-inline-item dropdown notification-list">
                                <i class="noti-icon"><div class:"img-fluid rounded-circle"></div></i>
                                <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class:"text-white"%>

                        </li>

                    </ul>

                </nav>

            </div>
            <!-- Top Bar End -->

app/views/superadmin/dashboard/shared/_right-content.html.erb
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <h4 class="page-title float-left">Bienvenue sur votre espace d'administration !</h4>

            <div class="clearfix"></div>
        </div>
    </div>
</div>
<!-- end row -->

<div class="row">
    <div class="col-xl-4 col-md-9">
        <div class="widget-panel widget-style-2 bg-white">
            <i class="ion-md-contacts text-info"></i>
            <h2 class="m-0" data-plugin="counterup"> @users.count </h2>
            <div style="color:#666F7B">Utilisateurs</div>
        </div>
    </div>
    <div class="col-xl-4 col-md-9">
        <div class="widget-panel widget-style-2 bg-white">
            <i class="ion-md-document text-pink"></i>
            <h2 class="m-0" data-plugin="counterup"> @articles.count </h2>
            <div style="color:#666F7B">Articles</div>
        </div>
    </div>
    <div class="col-xl-4 col-md-9">
        <div class="widget-panel widget-style-2 bg-white">
            <i class="ion-md-text text-purple"></i>
            <h2 class="m-0" data-plugin="counterup"> @comments.count </h2>
            <div style="color:#666F7B">Commentaires</div>
        </div>
    </div>
    
</div> <!-- end row -->

app/views/superadmin/dashboard/shared/_sidebar.html.erb
<!-- ========== Left Sidebar Start ========== -->
            <div class="left side-menu">
                <div class="slimscroll-menu" id="remove-scroll">

                    <!--- Sidemenu -->
                    <div id="sidebar-menu">
                        <!-- Left Menu Start -->
                        <ul class="metismenu" id="side-menu">
                            <li class="menu-title">Navigation</li>
                            <li>
                                <a href="<%= superadmin_path %>"><i class="ion-md-speedometer"></i> <span> Tableau de bord </span><span class="menu-arrow"></span></a>
                            </li>
                            <li>
                                <a href="<%= superadmin_sites_path %>"><i class="ion-md-browsers"></i> <span> Blogs </span><span class="menu-arrow"></span></a>
                            </li>
                            <li>
                                <a href="<%= superadmin_users_path %>"><i class="ion-md-contacts"></i> <span> Utilisateurs </span><span class="menu-arrow"></span></a>
                            </li>
                            <li>
                                <a href="<%= superadmin_products_path %>"><i class="ion-md-color-palette"></i> <span> Thèmes </span><span class="menu-arrow"></span></a>
                            </li>
                            <li>
                                <a href="<%= superadmin_sale_path %>"><i class="ion-md-pricetags"></i> <span> Ventes </span><span class="menu-arrow"></span></a>
                            </li>

                        </ul>

                    </div>
                    <!-- Sidebar -->
                    <div class="clearfix"></div>

                </div>
                <!-- Sidebar -left -->

            </div>
            <!-- Left Sidebar End -->