config/routes.rb
Rails.application.routes.draw do

  root 'main/landing#index'
  get 'handler/error' => 'main/landing#error'

  get 'cgu' => 'main/landing#cgu'

  #devise_for :users
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  scope 'superadmin', module: 'superadmin', as: "superadmin" do
    get '/' => 'dashboard#index'
    resources :sites
    resources :users
    resources :products
    get 'sale' => "products#sale"
  end


  scope ':site/admin', module: 'admin', as: "admin" do
    get '/' => "dashboard#index"
    get 'update_template' => "templates#update_template"
    resources :templates

    resources :articles
    resources :categories
    resources :tabs , except: [:index, :show ]

    resources :comments, except: [:new, :create, :update, :edit ]

    resources :products
    resources :plugins, except: [:new, :create ]
    resources :carts
    resources :cart_products
    resources :orders, except: [ :update, :edit, :destroy ]
    get '/admin/cart_products/:product_id' => 'carts#add', as: 'add_product_in_cart'
    get '/remove/:product_id' => 'carts#remove', as: 'remove_product_in_cart'

    post 'pay' => 'orders#pay'
    get 'buy' => 'orders#buy'
    get 'new_tab_category'      => 'tabs#new_tab_category'

    get '/menu' => 'tabs#index'

    resources :sites, except: [:index, :new, :show, :create, :destroy ]
    get '/site/configuration' => 'sites#edit'


    get 'dashboard/index' => "dashboard#index"
    get '*path',   :to => 'dashboard#error'

  end

  post ":site/new_comment" => "handler#new_comment"

  get ':site'                 => "handler#web"
  get ':site/:slug1'          => "handler#web"
  get ':site/:slug1/:slug2'   => "handler#web"

  namespace :main do
    get 'landing/index'
    get 'landing/show'

  end
  namespace :web do
    get 'main/index'
    get 'main/show'

  end

  namespace :admin do
    get 'dashboard/index'
    get 'dashboard/show'
    get 'dashboard/login'
    get 'dashboard/signup'
  end


end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_and_belongs_to_many :products

	validates :price, presence: true
	validates :price, numericality: { greather_than_or_equal_to: 1 }

end

app/controllers/admin/orders_controller.rb
module Admin

  class OrdersController < Admin::ApplicationController
    include CurrentCart
    before_action :set_cart, only: [:new, :create]
    before_action :set_order, only: [:show, :edit, :update, :destroy]
    before_action :redirect_if_cart_is_empty, only: :new

    def buy

      @total = @user.cart.total
      @total_stripe = @user.cart.total  * 100

    end

    def pay
      # Amount in cents
      @total = @user.cart.total
      @total_stripe = @user.cart.total  * 100

      @amount = @user.cart.total  * 100

      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Paiement template',
        :currency    => 'eur'
      )

      order = Order.new(user: @user)

      for product in @user.cart.products
        order.products << product

        template = Template.create(site: @site, product: product, slug: product.title)

        product.update(sale: (product.sale + 1))
      end

      order.price = @user.cart.total

      order.save
      @user.update(cart: Cart.create)

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end


    def index
      @orders = Order.where(user: @user)
    end

    def show
    end

    def new
      @order = Order.new
    end

    def edit
    end

    def create
      @order.cart = @cart

      respond_to do |format|
        if @order.save
          session.delete(:cart_id)
          format.html { redirect_to root_path, notice: "Commande validée" }

        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @order.update(order_params)
          format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @order.destroy
      respond_to do |format|
        format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      end
    end





    def new

    end

    def create
      # Amount in cents
      @amount = 500

      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )

      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => 'Paiement template',
        :currency    => 'eur'
      )

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end




    private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:theme, :price)
    end

    def redirect_if_cart_is_empty
      if @cart.cart_products.empty?
        redirect_to root_url, notice: "Votre panier est vide"
      end
    end
  end

end

app/views/admin/orders/_form.html.erb
<%= form_with(model: [:admin, order], local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :theme %>
    <%= form.text_field :theme %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/orders/buy.html.erb
<%= render 'admin/dashboard/shared/header' %>
<%= render 'admin/dashboard/shared/sidebar' %>

<div class="content-page">
    <div class="content">
<%= form_tag admin_pay_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Montant: <%= @total %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Polygones"
          data-amount="<%= @total_stripe %>"
          data-currency="Eur"
          data-email="<%= @user.email%>"></script>
<% end %>

</div>
</div>
<%= render 'admin/dashboard/shared/footer' %>

app/views/admin/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', admin_order_path(@site.url,@order) %> |
<%= link_to 'Back', admin_order_path(@site.url) %>

app/views/admin/orders/index.html.erb
<div class="content-page">
 	<div class="content">
 		<div class="container-fluid">
 			<div class="row">
 				<div class="col-12 col-xs-12">
 					<div class="card">
 						<div class="card-body">
 							<h4 class="m-b-30 m-t-0 header-title">Mes commandes</h4> <br/>

              <% if @orders.empty? %>
                <p>Vous n'avez pas encore acheté de thème.</p>
              <% else %>
                <table class="table table-striped mb-0">
                  <thead>
                    <tr>
                      <th>Date</th>
                      <th>Total</th>
                      <th colspan="3"></th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @orders.each do |order| %>
                      <tr>
                        <td><%= order.created_at.to_formatted_s(:fulldate) %></td>
                        <td><%= order.price %> €</td>
                        <td><%= link_to 'Voir', admin_order_path(@site.url, order) %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              <% end %>
 						</div>
 					</div>
 				</div>
 			</div>
 		</div>
 	</div>
 </div>


<br>

</div> </div>

app/views/admin/orders/new.html.erb
<div class="content-page">
 	<div class="content">
 		<div class="container-fluid">
 			<div class="row">
 				<div class="col-12 col-xs-12">
 					<div class="card">
 						<div class="card-body">
 							<h4 class="m-b-30 m-t-0 header-title">Confirmer la commande</h4>
              <div class="tab-content">
                <!-- shopping-cart start -->
                <div class="tab-pane active" id="shopping-cart">
                  <form action=" <% new_admin_order_path %>">
                    <div class="shop-cart-table">
                      <div class="table-content table-responsive">


                              <% for @product_in_cart in @cart.products %>
                                <%= render 'admin/carts/shared/cart_product', product_in_cart: @product_in_cart , edit_quantity: false, edit_remove: true %>
                              <% end %>

                        <br/>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6 col-sm-6 col-xs-12">
                        <div class="customer-login payment-details mt-30 mb-30">
                          <h4>Total : <%=  @cart.total %> €</h4>
                          <br/>
                         </div>
                      </div>
                    </div>
                  </div>
                </form>
                  
<%= form_tag admin_pay_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Montant: <%= @total %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Polygones"
          data-amount="<%= @total_stripe %>"
          data-currency="Eur"
          data-email="<%= @user.email%>"></script>
<% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/pay.html.erb
<%= render 'admin/dashboard/shared/header' %>
<%= render 'admin/dashboard/shared/sidebar' %>
<div class="content-page">
  <div class="content">
    <div class="container-fluid">
      <!-- Nouvelle catégorie -->
      <div class="row">
        <div class="col-12 col-xs-12">
          <div class="card">
            <div class="card-body">
              <h4 class="m-b-30 m-t-0 header-title">Merci !</h4> <br/>
							<p>Votre paiement de <strong><%= @total %></strong> euros a bien été enregistré.</p>
							<%= link_to 'Accéder à vos thèmes', admin_templates_path(@site.url), class:"btn btn-primary" %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<%= render 'admin/dashboard/shared/footer' %>

app/views/admin/orders/show.html.erb
<div class="content-page">
 	<div class="content">
 		<div class="container-fluid">
 			<div class="row">
 				<div class="col-12 col-xs-12">
 					<div class="card">
 						<div class="card-body">
 							<h4 class="m-b-30 m-t-0 header-title">Mes commandes</h4> <br/>
              <p>
              <strong>Date:</strong>
              <%= @order.created_at.to_formatted_s(:fulldate) %>
            </p>

            <p>
              <strong>Prix:</strong>
              <%= @order.price %> €
            </p>

            <p>
              <strong>Produit acheté :</strong>
              <% for product in @order.products %>
              <%= product.title %>
              <% end %>
            </p>
            

            </div>
 					</div>
 				</div>
 			</div>
 		</div>
 	</div>
 </div>	