config/routes.rb
Rails.application.routes.draw do

  root 'main/landing#index'
  get 'handler/error' => 'main/landing#error'

  get 'cgu' => 'main/landing#cgu'

  #devise_for :users
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  scope 'superadmin', module: 'superadmin', as: "superadmin" do
    get '/' => 'dashboard#index'
    resources :sites
    resources :users
    resources :products
    get 'sale' => "products#sale"
  end


  scope ':site/admin', module: 'admin', as: "admin" do
    get '/' => "dashboard#index"
    get 'update_template' => "templates#update_template"
    resources :templates

    resources :articles
    resources :categories
    resources :tabs , except: [:index, :show ]

    resources :comments, except: [:new, :create, :update, :edit ]

    resources :products
    resources :plugins, except: [:new, :create ]
    resources :carts
    resources :cart_products
    resources :orders, except: [ :update, :edit, :destroy ]
    get '/admin/cart_products/:product_id' => 'carts#add', as: 'add_product_in_cart'
    get '/remove/:product_id' => 'carts#remove', as: 'remove_product_in_cart'

    post 'pay' => 'orders#pay'
    get 'buy' => 'orders#buy'
    get 'new_tab_category'      => 'tabs#new_tab_category'

    get '/menu' => 'tabs#index'

    resources :sites, except: [:index, :new, :show, :create, :destroy ]
    get '/site/configuration' => 'sites#edit'


    get 'dashboard/index' => "dashboard#index"
    get '*path',   :to => 'dashboard#error'

  end

  post ":site/new_comment" => "handler#new_comment"

  get ':site'                 => "handler#web"
  get ':site/:slug1'          => "handler#web"
  get ':site/:slug1/:slug2'   => "handler#web"

  namespace :main do
    get 'landing/index'
    get 'landing/show'

  end
  namespace :web do
    get 'main/index'
    get 'main/show'

  end

  namespace :admin do
    get 'dashboard/index'
    get 'dashboard/show'
    get 'dashboard/login'
    get 'dashboard/signup'
  end


end

app/models/tab.rb
class Tab < ApplicationRecord

  validates :title,:item, presence: true

  belongs_to :site
  belongs_to :item, polymorphic: true
  enum nature: {category: "Category", article: "Article"}




end

app/controllers/admin/tabs_controller.rb
module Admin

class TabsController < Admin::ApplicationController
  before_action :set_tab, only: [ :edit, :update, :destroy]

  def index
    @tabs = @site.tabs
  end

  def new
    @tab = Tab.new
    @articles = Article.where(site: @site)
    @categories = Category.where(site: @site)
  end

  def edit_tab_category
  end

  def new_tab_category
    @tab = Tab.new
    @articles = Article.where(site: @site)
    @categories = Category.where(site: @site)
  end

  def edit
    @articles = Article.where(site: @site)
    @categories = Category.where(site: @site)
  end

  def create
    @tab = Tab.new(tab_params)
    @tab.site = @site

    respond_to do |format|
      if @tab.save
        @tab.update(url: "/#{@site.url}/#{@tab.item.slug}")
        format.html { redirect_to admin_menu_path @site.url, @menu, notice: 'Tab was successfully created.' }
      else
        @articles = Article.where(site: @site)
        @categories = Category.where(site: @site)
        format.html { render :new }
      end
    end
  end

  def update

    respond_to do |format|
      if @tab.update(tab_params)
        @tab.update(url: "/#{@site.url}/#{@tab.item.slug}")
        format.html { redirect_to admin_menu_path @site.url, @menu, notice: 'Tab was successfully updated.' }
      else

        @articles = Article.where(site: @site)
        @categories = Category.where(site: @site)
        format.html { render :edit }
      end
    end
  end

  def destroy
    @tab.destroy
    respond_to do |format|
      format.html { redirect_to admin_menu_path @site.url, notice: 'Tab was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tab
      @tab = Tab.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tab_params
      params.require(:tab).permit(:title, :order, :item_type, :item_id)
    end
end

end

app/views/admin/tabs/_form.html.erb
<%= form_with(model: [:admin, tab], local: true) do |form| %>
  <% if tab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tab.errors.count, "error") %> prohibited this tab from being saved:</h2>

      <ul>
      <% tab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :order %>
    <%= form.number_field :order %>
  </div>

  <div class="field">
    <%= form.label :menu_id %>
    <%= form.text_field :menu_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/tabs/edit.html.erb
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-9 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="m-b-30 m-t-0 header-title">Créer un onglet</h4>
                            <%= form_with(model: [:admin, @tab], local: true, url: admin_tab_path(@site.url)) do |form| %>
                              <% if @tab.errors.any? %>
                                <div id="error_explanation">
                                  <h2><%= pluralize(@tab.errors.count, "erreur") %> empêche cet onglet d'être sauvegardé :</h2>

                                  <ul>
                                  <% @tab.errors.full_messages.each do |message| %>
                                    <li><%= message %></li>
                                  <% end %>
                                  </ul>
                                </div>
                              <% end %>
                              <div class="form-row">
                                  <div class="form-group col-md-12">
                                    <%= form.label :title, class:"col-form-label label1" %>
                                    <%= form.text_field :title, autofocus: true, autocomplete: "Titre de votre onglet", class:"form-control" %>
                                  </div>
                              </div>

                              <% if @tab.item.instance_of? Article %>

                              <%= form.hidden_field :item_type, value: "Article" %>


                              <div class="form-row " id="article">
                                  <div class="form-group col-md-12">
                                    <%= form.label :id, "Séléctionner l'article", class:"col-form-label label1" %>
                                    <%= form.collection_select :item_id, @articles, :id, :title, prompt: true,required: true %>

                                  </div>
                              </div>

                              <% else %>

                              <%= form.hidden_field :item_type, value: 'Category' %>

                              <div class="form-row" id="category" >
                                  <div class="form-group col-md-12">

                                      <%= form.label :id, "Séléctionner la category", class:"col-form-label label1" %>
                                      <%= form.collection_select :item_id, @categories, :id, :title, prompt: true %>

                                  </div>
                              </div>


                              <% end %>



                              <div class="actions">
                                <%= form.submit :"Sauvegarder mon onglet", class:"btn btn-primary" %>
                              </div>

                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="m-b-30 m-t-0 header-title">Paramètres</h4>
                            <div class="form-row">
                                <div class="form-group col-md-12">

                                </div>
                            </div>

                            <div class="form-row">
                                <div class="form-group col-md-12">
                                  </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/admin/tabs/edit_tab_category.html.erb
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-9 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="m-b-30 m-t-0 header-title">Créer un onglet</h4>
                            <%= form_with(model: [:admin, @tab], local: true, url: admin_tab_path(@site.url)) do |form| %>
                              <% if @tab.errors.any? %>
                                <div id="error_explanation">
                                  <h2><%= pluralize(@tab.errors.count, "erreur") %> empêche cet onglet d'être sauvegardé :</h2>

                                  <ul>
                                  <% @tab.errors.full_messages.each do |message| %>
                                    <li><%= message %></li>
                                  <% end %>
                                  </ul>
                                </div>
                              <% end %>
                              <div class="form-row">
                                  <div class="form-group col-md-12">
                                    <%= form.label :title, class:"col-form-label label1" %>
                                    <%= form.text_field :title, autofocus: true, autocomplete: "Titre de votre onglet", class:"form-control" %>
                                  </div>
                              </div>

                              <%= form.hidden_field :item_type, value: 'Category' %>

                              <div class="form-row" id="category" >
                                  <div class="form-group col-md-12">

                                      <%= form.label :id, "Séléctionner la category", class:"col-form-label label1" %>
                                      <%= form.collection_select :item_id, @categories, :id, :title, prompt: true %>

                                  </div>
                              </div>

                              <div class="actions">
                                <%= form.submit :"Sauvegarder mon onglet", class:"btn btn-primary" %>
                              </div>

                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="m-b-30 m-t-0 header-title">Paramètres</h4>
                            <div class="form-row">
                                <div class="form-group col-md-12">

                                </div>
                            </div>

                            <div class="form-row">
                                <div class="form-group col-md-12">
                                  </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/admin/tabs/index.html.erb
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
            <div class="row">

                <div class="col-md-9 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="m-b-30 m-t-0 header-title">Mon menu</h4><br/>
                            <table class="table mb-0">
                                <tbody>

                                  <% @tabs.each do |tab| %>
                                    <tr>
                                      <td><%= tab.title %></td>
                                      <td><i class="far fa-edit"></i><%= link_to ' Editer', edit_admin_tab_path(@site.url,tab) %>


                                      </td>
                                      <td><i class="far fa-trash-alt"></i><%= link_to ' Supprimer', admin_tab_path(@site.url,tab), method: :delete, data: { confirm: 'Êtes-vous sûr·e?' } %></td>


                                    </tr>
                                  <% end %>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-xs-12">  
                    <div class="card">
                        <div class="card-body">
                            <h4 class="m-b-30 m-t-0 header-title">Configuration du menu</h4>
                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    <div class="field">
                                        <br/>
                                        <%= link_to 'Créer un nouvel onglet pour un article', new_admin_tab_path, class:"btn btn-primary", style:"white-space: normal;" %>
                                        <br/><br/>
                                        <%= link_to 'Créer un nouvel onglet pour une catégorie', admin_new_tab_category_path, class:"btn btn-primary", style:"white-space: normal;" %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin/tabs/new.html.erb
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12  col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="m-b-30 m-t-0 header-title">Créer un onglet pour un article </h4>
                            <%= form_with(model: [:admin, @tab], local: true) do |form| %>
                              <% if @tab.errors.any? %>
                                <div id="error_explanation">
                                  <h2><%= pluralize(@tab.errors.count, "erreur") %> empêche cet onglet d'être sauvegardé :</h2>

                                  <ul>
                                  <% @tab.errors.full_messages.each do |message| %>
                                    <li><%= message %></li>
                                  <% end %>
                                  </ul>
                                </div>
                              <% end %>
                              <div class="form-row">
                                  <div class="form-group col-md-12">
                                    <%= form.label :title, class:"col-form-label label1" %>
                                    <%= form.text_field :title, autofocus: true, autocomplete: "Titre de votre onglet", class:"form-control" %>
                                  </div>
                              </div>


                              <div class="form-row">

                                  <div class="form-group col-md-12">
                                    <%= form.hidden_field :item_type, value: "Article"%>

                                  </div>


                              </div>



                              <div class="form-row " id="article" >
                                  <div class="form-group col-md-12">
                                    <%= form.label :id, "Séléctionner l'article", class:"col-form-label label1" %>
                                    <%= form.collection_select :item_id, @articles, :id, :title, prompt: true,required: true %>

                                  </div>
                              </div>

                              <div class="actions">
                                <%= form.submit :"Créer mon onglet", class:"btn btn-primary" %>
                              </div>

                        </div>
                    </div>
                </div>

            </div>
            <% end %>


        </div>

    </div>
</div>

app/views/admin/tabs/new_tab_category.html.erb
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12  col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="m-b-30 m-t-0 header-title">Créer un onglet pour plusieurs articles</h4>
                            <%= form_with(model: [:admin, @tab], local: true) do |form| %>
                              <% if @tab.errors.any? %>
                                <div id="error_explanation">
                                  <h2><%= pluralize(@tab.errors.count, "erreur") %> empêche cet onglet d'être sauvegardé :</h2>

                                  <ul>
                                  <% @tab.errors.full_messages.each do |message| %>
                                    <li><%= message %></li>
                                  <% end %>
                                  </ul>
                                </div>
                              <% end %>
                              <div class="form-row">
                                  <div class="form-group col-md-12">
                                    <%= form.label :title, class:"col-form-label label1" %>
                                    <%= form.text_field :title, autofocus: true, autocomplete: "Titre de votre onglet", class:"form-control" %>
                                  </div>
                              </div>

                              <div class="form-row">
                                  <div class="form-group col-md-12">
                                    <%= form.hidden_field :item_type, value: "Category"%>
                                  </div>
                              </div>

                              <div class="form-row " id="article" >
                                  <div class="form-group col-md-12">
                                    <%= form.label :id, "Sélectionner la catégorie", class:"col-form-label label1" %>
                                    <%= form.collection_select :item_id, @categories, :id, :title, prompt: true,required: true %>

                                  </div>
                              </div>

                              <div class="actions">
                                <%= form.submit :"Créer mon onglet", class:"btn btn-primary" %>
                              </div>

                        </div>
                    </div>
                </div>

            </div>
            <% end %>


        </div>
    </div>
</div>

app/views/admin/tabs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tab.title %>
</p>

<p>
  <strong>Order:</strong>
  <%= @tab.order %>
</p>

<p>
  <strong>Menu:</strong>
  <%= @tab.menu %>
</p>

<%= link_to 'Edit', edit_tab_path(@tab) %> |
<%= link_to 'Back', tabs_path %>