config/routes.rb
Rails.application.routes.draw do

  root 'main/landing#index'
  get 'handler/error' => 'main/landing#error'

  get 'cgu' => 'main/landing#cgu'

  #devise_for :users
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  scope 'superadmin', module: 'superadmin', as: "superadmin" do
    get '/' => 'dashboard#index'
    resources :sites
    resources :users
    resources :products
    get 'sale' => "products#sale"
  end


  scope ':site/admin', module: 'admin', as: "admin" do
    get '/' => "dashboard#index"
    get 'update_template' => "templates#update_template"
    resources :templates

    resources :articles
    resources :categories
    resources :tabs , except: [:index, :show ]

    resources :comments, except: [:new, :create, :update, :edit ]

    resources :products
    resources :plugins, except: [:new, :create ]
    resources :carts
    resources :cart_products
    resources :orders, except: [ :update, :edit, :destroy ]
    get '/admin/cart_products/:product_id' => 'carts#add', as: 'add_product_in_cart'
    get '/remove/:product_id' => 'carts#remove', as: 'remove_product_in_cart'

    post 'pay' => 'orders#pay'
    get 'buy' => 'orders#buy'
    get 'new_tab_category'      => 'tabs#new_tab_category'

    get '/menu' => 'tabs#index'

    resources :sites, except: [:index, :new, :show, :create, :destroy ]
    get '/site/configuration' => 'sites#edit'


    get 'dashboard/index' => "dashboard#index"
    get '*path',   :to => 'dashboard#error'

  end

  post ":site/new_comment" => "handler#new_comment"

  get ':site'                 => "handler#web"
  get ':site/:slug1'          => "handler#web"
  get ':site/:slug1/:slug2'   => "handler#web"

  namespace :main do
    get 'landing/index'
    get 'landing/show'

  end
  namespace :web do
    get 'main/index'
    get 'main/show'

  end

  namespace :admin do
    get 'dashboard/index'
    get 'dashboard/show'
    get 'dashboard/login'
    get 'dashboard/signup'
  end


end

app/controllers/handler_controller.rb
class HandlerController < ApplicationController

  layout 'nature'

  def new_comment
    @comment = Comment.new(commentaire_params)
    @comment.article = Article.find(params['comment']['article'])

    @site = Site.find_by(url: params[:site])

    if @comment.save
         respond_to do |format|
            format.html { redirect_to root_path }
            format.js  { render "web/"+@site.template.slug+"/comment.js.erb"}
         end
    end

  end

  def commentaire_params
    params.require(:comment).permit(:name, :content)
  end

  def web

    @comment = Comment.new
    @comments = []

    @site = Site.find_by(url: params[:site])

    if(! @site )
      redirect_to handler_error_path
    else

    @tabs = @site.tabs

    if !params[:slug1]
      # page d'accueil du site

      if Tab.find_by(home: true, site: @site).item.instance_of? Article
        @article = Tab.find_by(home: true, site: @site).item
        hit = @article.hits + 1
        @article.update(hits: hit)
        render "web/#{@site.template.slug}/article"

      else
        @articles = Article.where(category: Tab.find_by(home: true, site: @site).item, site:  @site)
        render "web/#{@site.template.slug}/blog"

      end

      # todo
      # Attention il est posible que la page d'accueil soit une page categorie
    else
      #params[:slug1] existe

      if params[:slug2]
        # page article

        @article = @site.articles.find_by(slug: params[:slug2])
        if ! @article
          # article n'existe pas
          # faudrai le retourner a la page interne du template
          render handler_404_path
        else
          #render :index
          hit = @article.hits + 1
          @article.update(hits: hit)
          @comments = Comment.where(article: @article)

          render "web/#{@site.template.slug}/article"
        end

      else
        # page article ou categorie
        @article = @site.articles.find_by(slug: params[:slug1])
        if @article
          hit = @article.hits + 1
          @article.update(hits: hit)
          @comments = Comment.where(article: @article)
          render "web/#{@site.template.slug}/article"
        else


          @category = Category.find_by(slug: params[:slug1], site: @site)

          if @category
              @articles = @site.articles.where(category: @category)
              puts @articles

            render "web/#{@site.template.slug}/blog"
          else
            render handler_404_path
          end
        end
      end

    end


  end


  end


  def index
  	@products = Product.order(:title)
  end

  def error
  end

  def comming_soon
  end

  def inscription
  end

  def search

    site_name = params['q']

    @site_name = site_name


    if Site.exists?(url: site_name)
      @message_site_erreur = true
    else
      @message_site_valide = true
    end
    respond_to do |f|
      f.js
    end

  end

end

app/views/handler/404.html.erb
<h1>Handler - 404 </h1>
<p>Page introuvable</p>

app/views/handler/comming_soon.html.erb
<div class="main-area center-text" style="background-image:url(images/countdown-6-1600x900.jpg);" >

		<div class="display-table">
			<div class="display-table-cell">

				<h1 class="title"><b>Comming Soon</b></h1>
				<p class="desc font-white">Notre site est en construction.</p>
        <p class="desc font-white"> Ouverture le 17 septembre 2018 .</p>


				<div id="normal-countdown" data-date="2018/01/01"></div>



			</div><!-- display-table -->
		</div><!-- display-table-cell -->
	</div><!-- main-area -->

app/views/handler/error.html.erb
<%= stylesheet_link_tag :admin %>

            <div class="wrapper-page">
                <div class="account-pages">
                    <div class="account-box">
                        <div class="account-logo-box bg-primary p-4">
                            <h3 class="m-0 text-center text-white"><%= image_tag 'main/logo.png', alt:"logo", height:"40" %></h3>
                        </div>
                        <div class="account-content text-center">
                                <h1 class="text-error display-4 font-weight-bold">404</h1>
                            <h3 class="text-uppercase font-weight-bold text-danger m-t-30">Il n'y a rien ici !</h3>
                            <p class="text-muted mt-3">Vous ne pouvez pas accéder à cette page. Si vous essayez d'accéder à votre console d'administration, veuillez vous <%= link_to "connecter", new_user_session_path %></p>

                            <%= link_to "Retourner vers l'accueil", root_path, class:"btn btn-md btn-block btn-primary waves-effect waves-light m-t-20" %>
                        </div>
                    </div>
                </div>
                <!-- end account-box-->


            </div>

app/views/handler/index.html.erb
<%= link_to "Gestion des articles", admin_articles_path %> <br/>
<%= link_to "Gestion des categories", admin_categories_path %><br/>

<%= link_to "Voir mon compte", edit_user_registration_path %><br/>
<%= link_to "Gestion de mon site", admin_site_configuration_path %><br/>
<%= link_to "Gestion du menu", admin_site_menu_path %><br/>


<%if user_signed_in? %>
<%= link_to "Deconnexion", destroy_user_session_path, method: :delete %><br/>
<% end %>


<h1>Catalogue produit</h1>

<% @products.each do |product| %>
  <div class="row mb-4">
    <div class="card w-50 bg-light">
      <div class="card-body">
        <h2 class="card-title"><%= product.title %></h2>
      </div>
      <div class="card-footer text-center font-weight-bold">
        <%= number_to_currency product.price, unit: '€', separator: ',', format: '%n %u' %>
        <%= link_to "Ajouter au panier", cart_products_path(product_id: product), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/handler/web.html.erb
render '/web/nature/article'

<%= @site.name %>